#! /usr/bin/env python3

"""
Analyses Zenodo JSON file generated by fetch.py, and generates reports in Markdown and HTML
"""

import sys
import os
import shutil
import codecs
import json
import datetime
from dateutil import rrule
import pandas as pd
import numpy as np
from matplotlib import pylab
from matplotlib import pyplot as plt
from matplotlib import dates as mdates
from matplotlib.dates import DateFormatter
import markdown
from tabulate import tabulate
from . import config

# Set defaults for pyplot
params = {'legend.fontsize': 'large',
          'figure.figsize': (16, 9),
         'axes.labelsize': '18',
         'axes.titlesize':'large',
         'xtick.labelsize':'x-large',
         'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)

def dfToMarkdown(dataframe, headers='keys'):
    """Convert Data Frame to Markdown table with optionally custom headers"""
    mdOut = dataframe.pipe(tabulate, headers=headers, tablefmt='pipe')
    return mdOut


def iterateAggregation(aggregation):
    """Iterate over aggregation elements and return output table as list"""
    buckets = aggregation["buckets"]
    countOther = aggregation["sum_other_doc_count"]

    outTable = []

    for bucket in buckets:
        doc_count = bucket["doc_count"]
        key = bucket["key"]
        outTable.append([key, doc_count])

    outTable.append(['other', countOther])

    return outTable


def reportAccessRights(aggregations):
    """Report access right info"""
    access_right = aggregations["access_right"]
    outTable = iterateAggregation(access_right)

    # Create summary table
    tableHeader = ['Access type', 'Number of publications']

    mdString = '\n\n## Access rights\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportFileTypes(aggregations):
    """Report file type info"""
    file_type = aggregations["file_type"]
    outTable = iterateAggregation(file_type)

    # Create summary table
    tableHeader = ['File type', 'Number of files']

    mdString = '\n\n## File types\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportKeywords(aggregations):
    """Report keyword info"""
    keywords = aggregations["keywords"]
    outTable = iterateAggregation(keywords)

    # Create summary table
    tableHeader = ['Keyword', 'Number of publications']

    mdString = '\n\n## Keywords\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportPublicationTypes(aggregations):
    """Report publication type info"""
    type = aggregations["type"]
    outTable = iterateAggregation(type)

    # Create summary table
    tableHeader = ['Publication type', 'Number of publications']

    mdString = '\n\n## Publication types\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def frequenciesByMonth(datesIn):
    """Takes list of datetime strings, and returns data frame
    with frequencies and cumulative frequencies by month"""

    dates = []
    # First convert ISO datetime strings to date values
    for dateIn in datesIn:
        dates.append(datetime.datetime.fromisoformat(dateIn).date())
    
    # Sort dates and get lower/upper bounds
    dates.sort()
    yearMin = dates[0].year
    monthMin = dates[0].month
    yearMax = dates[len(dates) - 1].year
    monthMax = dates[len(dates) - 1].month

    # List of all months between dateMin and dateMax
    dateRange = []

    year = yearMin
    month = monthMin

    while year <= yearMax:
        myDate = datetime.date(year, month, 1)
        dateRange.append(myDate)
        if year == yearMax:
            if month < monthMax:
                month += 1
            else:
                # Increase year index to force break from loop
                year += 1
        else:
            month +=1
        if month > 12:
            month = 1
            year += 1

        dateCounts = []
        dateCountsCum = []

    countCumPrev = 0

    # For each month in dateRange, count number of dates
    # and keep track of cumulative count
    for month in dateRange:
        count = 0
        for date in dates:
            if date.year == month.year and date.month == month.month:
                count += 1
        dateCounts.append(count)
        countCum = countCumPrev + count
        dateCountsCum.append(countCum)
        countCumPrev = countCum

    datesFrame = pd.DataFrame({'date': dateRange,
                                'freq': dateCounts,
                                'freqCum': dateCountsCum})

    return datesFrame, yearMin, yearMax


def plotDfTime(dataFrame, xCol, yCol, xLabel, yLabel, yearMin, yearMax, imageOut):
    """Plot time-based data frame"""
    myPlot = dataFrame.plot(kind='line',
                                x=xCol,
                                y=yCol,
                                lw=2.5,
                                figsize=(16,9))

    # Note: setting 'kind' to 'box' babove results in weird
    # behaviour if date_form is used (all years are set to 1970)!
    # Might be related to this bug: https://github.com/pandas-dev/pandas/issues/26253

    date_form = DateFormatter("%Y-%m")
    myPlot.axes.xaxis.set_major_formatter(date_form)

    locator = mdates.AutoDateLocator(minticks = 16, maxticks = 24)
    formatter = mdates.ConciseDateFormatter(locator)
    formatter.formats = ['%Y', '%b', '%d']

    myPlot.axes.xaxis.set_major_locator(locator)
    myPlot.axes.xaxis.set_major_formatter(formatter)

    myPlot.set_xlabel(xLabel)
    myPlot.set_ylabel(yLabel)
    myPlot.set_xlim([datetime.date(yearMin, 1, 1), datetime.date(yearMax, 12, 31)])
    myPlot.get_legend().remove()
    fig = myPlot.get_figure()
    fig.savefig(imageOut)


def reportCreatedDates(createdDates):
    """Report created dates info"""

    # Analyse created dates
    cDatesFrame, yearMin, yearMax = frequenciesByMonth(createdDates)

    # Export data frame to a CSV file
    cDatesFrame.to_csv(os.path.join(config.dirCSV, 'pubsTime.csv'), encoding='utf-8', index=False)

    # Plot frequencies
    xLabel = 'Datum'
    yLabel = 'Publicaties'
    imageOut = os.path.join(config.dirImg, 'publicaties-tijd.png')
    plotDfTime(cDatesFrame, 'date', 'freq', xLabel, yLabel, yearMin, yearMax, imageOut)

    # Plot cumulative frequencies
    xLabel = 'Datum'
    yLabel = 'Publicaties (cumulatief)'
    imageOut = os.path.join(config.dirImg, 'publicaties-tijd-cum.png')
    plotDfTime(cDatesFrame, 'date', 'freqCum', xLabel, yLabel, yearMin, yearMax, imageOut)
 

def reportPublicationDates(publicationDates):
    """Report publication dates info"""
    pubDates = []
    for publicationDate in publicationDates:
        pubDates.append(datetime.date.fromisoformat(publicationDate))
    print(pubDates)


def report(fileIn):
    """Create report from JSON file"""

    dirOut = os.path.join('.', 'report')
    if not os.path.isdir(dirOut):
        os.makedirs(dirOut)

    config.dirCSS = os.path.join(dirOut, 'css')
    config.dirCSV = os.path.join(dirOut, 'csv')
    config.dirImg = os.path.join(dirOut, 'img')

    if not os.path.isdir(config.dirCSS):
        os.makedirs(config.dirCSS)

    if not os.path.isdir(config.dirCSV):
        os.makedirs(config.dirCSV)

    if not os.path.isdir(config.dirImg):
        os.makedirs(config.dirImg)

    # Copy style sheet to CSS dir
    try:
        cssIn = os.path.join(sys.path[0], 'css', 'github-markdown.css')
        cssOut = os.path.join(config.dirCSS, 'github-markdown.css')
        shutil.copyfile(cssIn, cssOut)
    except:
        sys.stderr.write("Cannot copy style sheet\n")
        sys.exit()

    # Initialize empty string for Markdown output
    reportString = ""

    # Read JSON file
    with open(fileIn, 'r') as f:
        dataIn = json.load(f)

    # Report aggregated statistics
    aggregations = dataIn["aggregations"]
    mdString = reportAccessRights(aggregations)
    reportString += mdString
    mdString = reportFileTypes(aggregations)
    reportString += mdString
    mdString = reportKeywords(aggregations)
    reportString += mdString
    mdString = reportPublicationTypes(aggregations)
    reportString += mdString
 
    # Report detailed statistics from individual hits
    hits = dataIn["hits"]["hits"]
    createdDates = []
    fileTypes = []
    accessRights = []
    keyWords = []
    languages = []
    licenses = []
    publicationDates = []
    resourceTypes = []
    resourceSubtypes = []

    for hit in hits:
        created = hit["created"]
        createdDates.append(created)
        try:
            files = hit["files"]
        except KeyError:
            # Closed access publications can have no files
            files = []
        for file in files:
            ftype = file["type"]
            fileTypes.append(ftype)
        metadata = hit["metadata"]
        access_right = metadata["access_right"]
        accessRights.append(access_right)
        try:
            keywords = metadata["keywords"]
        except KeyError:
            keywords = []
        for keyword in keywords:
            keyWords.append(keyword)
        try:
            language = metadata["language"]
            languages.append(language)
        except KeyError:
            languages.append("N/A")
        try:
            license = metadata["license"]["id"]
            licenses.append(license)
        except KeyError:
            licenses.append("N/A")
        try:
            publicationDate = metadata["publication_date"]
            publicationDates.append(publicationDate)
        except KeyError:
            publicationDates.append("N/A")
        resource_type = metadata["resource_type"]
        
        try:
            type = resource_type["type"]
            resourceTypes.append(type)
        except KeyError:
            pass
        try:
            subtype = resource_type["subtype"]
            resourceSubtypes.append(subtype)
        except KeyError:
            pass

    reportCreatedDates(createdDates)

