#! /usr/bin/env python3

"""
Analyses Zenodo JSON file generated by fetch.py, and generates reports in Markdown and HTML
"""

import sys
import os
import shutil
import codecs
import json
import datetime
import pandas as pd
import numpy as np
from matplotlib import pylab
import markdown
from tabulate import tabulate

# Set defaults for pyplot
params = {'legend.fontsize': 'x-large',
          'figure.figsize': (8, 6),
         'axes.labelsize': '18',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'x-large',
         'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)


def dfToMarkdown(dataframe, headers='keys'):
    """Convert Data Frame to Markdown table with optionally custom headers"""
    mdOut = dataframe.pipe(tabulate, headers=headers, tablefmt='pipe')
    return mdOut


def iterateAggregation(aggregation):
    """Iterate over aggregation elements and return output table as list"""
    buckets = aggregation["buckets"]
    countOther = aggregation["sum_other_doc_count"]

    outTable = []

    for bucket in buckets:
        doc_count = bucket["doc_count"]
        key = bucket["key"]
        outTable.append([key, doc_count])

    outTable.append(['other', countOther])

    return outTable


def reportAccessRights(aggregations):
    """Report access right info"""
    access_right = aggregations["access_right"]
    outTable = iterateAggregation(access_right)

    # Create summary table
    tableHeader = ['Access type', 'Number of publications']

    mdString = '\n\n## Access rights\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportFileTypes(aggregations):
    """Report file type info"""
    file_type = aggregations["file_type"]
    outTable = iterateAggregation(file_type)

    # Create summary table
    tableHeader = ['File type', 'Number of files']

    mdString = '\n\n## File types\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportKeywords(aggregations):
    """Report keyword info"""
    keywords = aggregations["keywords"]
    outTable = iterateAggregation(keywords)

    # Create summary table
    tableHeader = ['Keyword', 'Number of publications']

    mdString = '\n\n## Keywords\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportPublicationTypes(aggregations):
    """Report publication type info"""
    type = aggregations["type"]
    outTable = iterateAggregation(type)

    # Create summary table
    tableHeader = ['Publication type', 'Number of publications']

    mdString = '\n\n## Publication types\n\n'
    mdString += tabulate(outTable, tableHeader, tablefmt='pipe')

    return mdString


def reportCreatedDates(createdDates):
    """Report created dates info"""
    cDates = []
    # First convert everything to datetime values
    for createdDate in createdDates:
        cDates.append(datetime.datetime.fromisoformat(createdDate))
    
    # Sort dates and get lower/upper bounds
    cDates.sort()
    dateMin = cDates[0]
    dateMax = cDates[len(cDates) - 1]

    # TODO:
    #
    # - Create list of all months between dateMin and dateMax
    # - For each month, count number of publications created that month
    # - Report as bar chart, table, CSV
 
    print(dateMin, dateMax)


def reportPublicationDates(publicationDates):
    """Report publication dates info"""
    pubDates = []
    for publicationDate in publicationDates:
        pubDates.append(datetime.date.fromisoformat(publicationDate))
    print(pubDates)

def report(fileIn):
    """Create report from JSON file"""

    # Initialize empty string for Markdown output
    reportString = ""

    # Read JSON file
    with open(fileIn, 'r') as f:
        dataIn = json.load(f)

    # Report aggregated statistics
    aggregations = dataIn["aggregations"]
    mdString = reportAccessRights(aggregations)
    reportString += mdString
    mdString = reportFileTypes(aggregations)
    reportString += mdString
    mdString = reportKeywords(aggregations)
    reportString += mdString
    mdString = reportPublicationTypes(aggregations)
    reportString += mdString
 
    # Report detailed statistics from individual hits
    hits = dataIn["hits"]["hits"]
    createdDates = []
    fileTypes = []
    accessRights = []
    keyWords = []
    languages = []
    licenses = []
    publicationDates = []
    resourceTypes = []
    resourceSubtypes = []

    for hit in hits:
        created = hit["created"]
        createdDates.append(created)
        try:
            files = hit["files"]
        except KeyError:
            # Closed access publications can have no files
            files = []
        for file in files:
            ftype = file["type"]
            fileTypes.append(ftype)
        metadata = hit["metadata"]
        access_right = metadata["access_right"]
        accessRights.append(access_right)
        try:
            keywords = metadata["keywords"]
        except KeyError:
            keywords = []
        for keyword in keywords:
            keyWords.append(keyword)
        try:
            language = metadata["language"]
            languages.append(language)
        except KeyError:
            languages.append("N/A")
        try:
            license = metadata["license"]["id"]
            licenses.append(license)
        except KeyError:
            licenses.append("N/A")
        try:
            publicationDate = metadata["publication_date"]
            publicationDates.append(publicationDate)
        except KeyError:
            publicationDates.append("N/A")
        resource_type = metadata["resource_type"]
        
        try:
            type = resource_type["type"]
            resourceTypes.append(type)
        except KeyError:
            pass
        try:
            subtype = resource_type["subtype"]
            resourceSubtypes.append(subtype)
        except KeyError:
            pass

    reportCreatedDates(createdDates)
    #reportPublicationDates(publicationDates)
    #for lan in createdDates:
    #    print(lan)

